# Generated by Django 4.0.1 on 2022-01-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_username_profile_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media\\default.jpg', upload_to='profile_pics'),
        ),
    ]
