# Generated by Django 4.0.1 on 2022-01-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='secret_key',
        ),
    ]
