# Generated by Django 4.0.1 on 2022-01-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binanceprofile',
            name='positions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
