# Generated by Django 4.0.2 on 2022-02-15 18:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('binance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Binance_profile',
            new_name='BinanceProfile',
        ),
    ]
