# Generated by Django 4.0.2 on 2022-02-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binance_app', '0002_rename_binance_profile_binanceprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('amount', models.FloatField(db_index=True, default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binance_app.binanceprofile')),
            ],
        ),
    ]
