# Generated by Django 4.0.1 on 2022-01-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binance_app', '0003_order_marketorder_stpmarket_trailingstopmarket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='binance_app.binanceprofile'),
            preserve_default=False,
        ),
    ]
