# Generated by Django 4.0.1 on 2022-01-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binance_app', '0004_currency_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='profile',
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binance_app.binanceprofile'),
        ),
    ]
