# Generated by Django 4.0.2 on 2022-02-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio_insight_followerscount'),
        ('binance_app', '0005_alter_binanceprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binanceprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
