# Generated by Django 4.0.2 on 2022-02-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binance_app', '0006_alter_binanceprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binanceprofile',
            old_name='user',
            new_name='profile',
        ),
    ]
