# Generated by Django 4.0.2 on 2022-02-16 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio_insight_followerscount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('binance_app', '0010_binanceprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binanceprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='binanceprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
