# Generated by Django 4.0.2 on 2022-02-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binance_app', '0011_alter_binanceprofile_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binanceprofile',
            name='profile',
        ),
    ]
