# Generated by Django 4.0.2 on 2022-02-16 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('binance_app', '0012_remove_binanceprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binanceprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
